// <auto-generated />
using System;
using EcrituresApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcritureComptable.Migrations
{
    [DbContext(typeof(ComptaDbContext))]
    partial class ComptaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcritureComptable.Models.AuditSuppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSuppression")
                        .HasColumnType("datetime2");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Motif")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NumeroEcriture")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AuditSuppressions");
                });

            modelBuilder.Entity("EcrituresApi.Models.Ecriture", b =>
                {
                    b.Property<decimal>("CleMvt")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("clemvt");

                    b.Property<string>("Compte_comptable")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DEVISE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("ETABLISSEMENT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Journal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Libelle_Ecriture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MONTANT_DEVISE")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Montant")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("N_Ecriture")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Reference_Piece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section_Analytique")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sens")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Societe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TYPE_PIECE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tiers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CleMvt");

                    b.ToTable("mvt_Mouvements", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
